version: '3'

services:
  vaultwarden-caddy:
    image: ghcr.io/ajhalili2006/vaultwarden-paas-starter:localdev
    build: .
    container_name: vaultwarden
    restart: unless-stopped # change this to always if needed, but please use f**king Kubernetes instead.
    environment:
      - WEBSOCKET_ENABLED=true # Enable WebSocket notifications on local deployments. Proxying stuff in Railway is gonna be bloddy hell.
    volumes:
      - ./data/vaultwarden-appdata:/data # Vaultvarden data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # Caddyfile
      - ./data/caddy-config:/config # caddy config
      - ./data/caddy-data:/data # caddy data
    environment:
      - LOG_FILE=/data/access.log
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    env_file: 
      - caddy.env
      - .env
  db:
    image: postgres:13-alpine